In [1]:
import numpy as np

In [25]:
# Layer 1
"""
Input = (1x2), weights is (2x2), output of first layer is (1x2). We add a bias to this, same shape
(1x2). 
"""
X = np.array([[2,4]]) # input
W1 = np.array([[1, 2], [3, 4]]) #2x2
b1 = np.array([[1,1]]) # 1x2



# Layer 2
"""Input is the output of layer 1, therefore we have an input of (1x2). We have weights (2x1), output is thus 
(1x1), to which we add a bias, shape (1x1).
"""


# Define the activated output of layer 1 as the input of layer 2
# a = np.array([[a1, a2]])


W2 = np.array([[2], [1]])
b2 = np.array([[1]])

# Print the shapes
print(W1.shape, b1.shape, W2.shape, b2.shape)

(2, 2) (1, 2) (2, 1) (1, 1)


In [37]:
# Randomize the weights to have random values between -1 and 1, if using tanh()
# np.random.rand gives values between 0 and 1, thus by shifting we get -1 to 1.
W1 = 2*np.random.rand(2,2)-1

# For sigmoid have values between 0 and 1
W1 = np.random.rand(2,2)
W2 = np.random.rand(2,1)

In [38]:
# to forward information from layer 1 to layer 2
"""sigmoidf(x dot W1 + b1)"""
def sigmoidf(x):
    """Sigmoid always returns a value between 0 and 1"""
    return (1 + np.exp(-x)) ** -1

# output layer 1:
a1 = sigmoidf(np.dot(X, W1)+b1)

In [39]:
a1

array([[0.95826956, 0.97264492]])

In [41]:
# second layer
y = sigmoidf(np.dot(a1, W2)+b2)
y

array([[0.79003668]])

In [42]:
# Define network
def XOR_net(X, W1, W2, b1, b2):    
    a1 = sigmoidf(np.dot(X, W1)+b1)
    a2 = sigmoidf(np.dot(a1, W2)+b2)
    return a2


In [47]:
# Garbage output - no training yet
XOR_net(np.array([[0,0]]), np.random.rand(2,2), np.random.rand(2,1), np.array([1,1]), np.array([[1]]))

array([[0.73551216]])

In [90]:
def random_weights(depth):
    """Create 'weights' per non-input node, first 2 are random, last is bias of value 1"""
    weights = np.random.rand(1,2)
    weights = np.append(weights, 1)
    for i in range(depth-1):
        weights = np.append(weights, np.random.rand(1,2))
        weights = np.append(weights, 1)
    return weights

# test
random_weights(3)

# to get shape 2x3
random_weights(3)[:6].reshape(2,3)

array([[0.95988957, 0.02165902, 1.        ],
       [0.55114024, 0.40350574, 1.        ]])

In [96]:
# Using what is asked in the exercise
def XOR_net_V2(inputs, weights):   
    """
    Inputs: array 
    weights: (1x9) matrix, the non-input nodes each have 3 weights, 2 incoming, and a bias.
    weights is created in such a way that the first 2 are the (random) weights and the last is the bias
    of node 1, 2 or final.
    """
    a1 = sigmoidf(np.dot(inputs, weights[:6].reshape(2,3)))
    a2 = sigmoidf(np.dot(a1, weights[6:].reshape(3,1)))
    return a2.reshape((1))

In [97]:
# Example
XOR_net_V2(np.array([[1,0]]), random_weights(3))

array([0.75199649])

In [105]:
# Implement the error function - use the mean squared error
def mse(weights, inputs, outputs, net=XOR_net_V2):
    # Calculate the mean squared error over all input and outputs from our network, we divide by
    # the length of the outputs to obtain the mean over all squared errors.
    return sum([(net(inpt, weights) - output)** 2 for inpt, output in zip(inputs, outputs)])/len(outputs)


In [107]:
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outputs = np.array([0, 1, 1, 0])

# Example
mse(random_weights(3), inputs, outputs, net=XOR_net_V2)

array([0.30433549])

In [108]:
# Implement the gradient of the mse function, grdmse


