In [8]:
import numpy as np

x = np.array([0, 1])  # inputs
w1 = np.array([[1, 2], [3, 4]]).T
b1 = np.array([0, 0])

np.dot(w1, x) + b1
w1

array([[1, 3],
       [2, 4]])

In [164]:
def sigmoid(x):
    return (1 + np.exp(-x)) ** -1


def random_weights(shape, min=-1, max=1):
    return (max - min) * np.random.random(shape) + min


def xor_net(inputs: np.ndarray, weights: np.ndarray):
    """Simulates a Neural Network for {2, 2, 1} architecture.

    Args:
        inputs (np.ndarray): 1x2 array representing the input nodes
        weights (np.ndarray): 1x9 array representing the weights and biases of the network

    Returns:
        int: output of the network. Range of values: (0, 1)
    """
    inputs = np.append(inputs, 1)  # add bias `value`
    hidden = np.dot(weights[:6].reshape((2, 3)), inputs)
    layer1 = sigmoid(hidden)

    layer1 = np.append(layer1, 1)  # add bias `value`
    final = np.dot(weights[6:], layer1)

    return sigmoid(final)


def mse(weights, inputs, outputs, net=xor_net):
    return sum(
        [(net(inpt, weights) - output) ** 2 for inpt, output in zip(inputs, outputs)]
    )


def grdmse(weights, inputs, outputs):
    par_derivs = np.zeros((9))
    for inpt, output in zip(inputs, outputs):
        inpt = np.append(inpt, 1)
        hidden = np.dot(weights[:6].reshape((2, 3)), inpt)
        layer1 = np.append(sigmoid(hidden), 1)
        final = sigmoid(np.dot(weights[6:], layer1))

        # These were derived by hand
        t = 2 * (final - output) * final * (1 - final)
        par_derivs[6:] += t * layer1
        par_derivs[3:6] += t * weights[7] * layer1[1] * (1 - layer1[1]) * inpt
        par_derivs[:3] += t * weights[6] * layer1[0] * (1 - layer1[0]) * inpt
    return par_derivs


def print_test(weights, inputs, outputs):
    for inpt, output in zip(inputs, outputs):
        print(f"{inpt[0]} | {inpt[1]} = {xor_net(inpt, weights):.3f} [{output}]")
    print(f"final mse: {mse(weights, inputs, outputs)}")


def grad_desc(eta=0.01, n_loops: int = 1000):
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

    outputs = np.array([0, 1, 1, 0])
    weights = random_weights((9))

    for i in range(n_loops):
        weights += -eta * grdmse(weights, inputs, outputs)

    print_test(weights, inputs, outputs)
    print(weights.reshape((3, 3)))


inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

outputs = np.array([0, 1, 1, 0])

grad_desc(eta=0.1, n_loops=10000)

0 | 0 = 0.030 [0]
0 | 1 = 0.971 [1]
1 | 0 = 0.966 [1]
1 | 1 = 0.027 [0]
final mse: 0.0036457123175088627
[[-5.27944364  4.99767172 -2.69384639]
 [-6.05835988  6.0039733   3.15041741]
 [ 8.64778262 -8.11234668  3.76172572]]


In [134]:
satisfied = False
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

outputs = np.array([0, 1, 1, 0])


def discretize(x):
    return 1 if x > 0.5 else 0


def test_random():
    weights = random_weights((9))
    for inpt, output in zip(inputs, outputs):
        if discretize(xor_net(inpt, weights)) != output:
            return False
    print(weights.reshape((3, 3)))
    return True


i = 0
while not test_random():
    i += 1
print(i)

[[-0.85890938 -0.90908956 -0.81769077]
 [ 0.47918798  0.51980033  0.00393972]
 [-0.91870358 -0.89549143  0.7162366 ]]
274604


In [ ]:
def sigmoid(x):
    return (1 + np.exp(-x)) ** -1


def dsigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))


def relu(x, a=1):
    return a * x if x > 0 else 0


def drelu(x, a=1):
    return a if x > 0 else 0